[package]
name = "a-search-for-poor-polynomial-approximations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools-num = "0.1.3"
kdam = "0.2.7"
plotters = "0.3.4"
rand = "0.8.5"
